name: Gemini AI Bot

on:
  push:
    branches: [ "main", "основной" ] # Сработает при сохранении
  workflow_dispatch:              # Кнопка ручного запуска

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Bot
        env:
          TG_TOKEN: ${{ secrets.TG_TOKEN }}
          GEMINI_KEY: ${{ secrets.GEMINI_KEY }}
        run: python bot.py
        
